name: ninaverde_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  url_launcher: ^6.3.2
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  rename: ^3.0.2
  build_runner: ^2.6.0     # <-- stay on 2.6.0 (compatible with meta 1.16.0)
  freezed: ^3.2.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.jpg

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21
