// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtPEEwLdVQgjMqB1xVaiJ1ZX0bEhBtKk4',
    appId: '1:615971922286:web:b83d41ce4213dc413e217f',
    messagingSenderId: '615971922286',
    projectId: 'e-commerce-nina-verde-vy-451f6',
    authDomain: 'e-commerce-nina-verde-vy-451f6.firebaseapp.com',
    storageBucket: 'e-commerce-nina-verde-vy-451f6.firebasestorage.app',
    measurementId: 'G-ZPQPWYR9HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtov3s_-0XQry_wX1MS_ow1I9MK2AhQss',
    appId: '1:615971922286:android:935491395ef212d33e217f',
    messagingSenderId: '615971922286',
    projectId: 'e-commerce-nina-verde-vy-451f6',
    storageBucket: 'e-commerce-nina-verde-vy-451f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQkHpFANwFQN186QsNHsXu_js7pRkK7gc',
    appId: '1:615971922286:ios:54f59fdef62cb6413e217f',
    messagingSenderId: '615971922286',
    projectId: 'e-commerce-nina-verde-vy-451f6',
    storageBucket: 'e-commerce-nina-verde-vy-451f6.firebasestorage.app',
    androidClientId:
        '615971922286-00shfu8caqeophjnov67tt23obp5qucs.apps.googleusercontent.com',
    iosClientId:
        '615971922286-227liageocvlmd4elaa1tn3jhrojtrl6.apps.googleusercontent.com',
    iosBundleId: 'com.nicaraguaninaverde.theapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQkHpFANwFQN186QsNHsXu_js7pRkK7gc',
    appId: '1:615971922286:ios:555c3a35a92bd5e13e217f',
    messagingSenderId: '615971922286',
    projectId: 'e-commerce-nina-verde-vy-451f6',
    storageBucket: 'e-commerce-nina-verde-vy-451f6.firebasestorage.app',
    androidClientId:
        '615971922286-00shfu8caqeophjnov67tt23obp5qucs.apps.googleusercontent.com',
    iosClientId:
        '615971922286-u8pgdiie70hqas7s03dh4fp8ndb3u4g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ninaverdeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvBoGjWPzW_kmBOXnwQPLdTRx-tRij6Bo',
    appId: '1:615971922286:web:c82169551a49eabb3e217f',
    messagingSenderId: '615971922286',
    projectId: 'e-commerce-nina-verde-vy-451f6',
    authDomain: 'e-commerce-nina-verde-vy-451f6.firebaseapp.com',
    storageBucket: 'e-commerce-nina-verde-vy-451f6.firebasestorage.app',
    measurementId: 'G-1ZPNDRTZ88',
  );
}
