// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _require('FIREBASE_WEB_API_KEY'),
        appId: _require('FIREBASE_WEB_APP_ID'),
        messagingSenderId: _require('FIREBASE_WEB_MESSAGING_SENDER_ID'),
        projectId: _require('FIREBASE_WEB_PROJECT_ID'),
        authDomain: _require('FIREBASE_WEB_AUTH_DOMAIN'),
        storageBucket: _require('FIREBASE_WEB_STORAGE_BUCKET'),
        measurementId: _optional('FIREBASE_WEB_MEASUREMENT_ID'),
      );

  static FirebaseOptions get android => const FirebaseOptions(
        apiKey: 'AIzaSyDtov3s_-0XQry_wX1MS_ow1I9MK2AhQss',
        appId: '1:615971922286:android:935491395ef212d33e217f',
        messagingSenderId: '615971922286',
        projectId: 'e-commerce-nina-verde-vy-451f6',
        storageBucket: 'e-commerce-nina-verde-vy-451f6.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _require('FIREBASE_IOS_API_KEY'),
        appId: _require('FIREBASE_IOS_APP_ID'),
        messagingSenderId: _require('FIREBASE_IOS_MESSAGING_SENDER_ID'),
        projectId: _require('FIREBASE_IOS_PROJECT_ID'),
        storageBucket: _require('FIREBASE_IOS_STORAGE_BUCKET'),
        androidClientId: _optional('FIREBASE_IOS_ANDROID_CLIENT_ID'),
        iosClientId: _optional('FIREBASE_IOS_CLIENT_ID'),
        iosBundleId: _require('FIREBASE_IOS_BUNDLE_ID'),
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: _require('FIREBASE_MACOS_API_KEY'),
        appId: _require('FIREBASE_MACOS_APP_ID'),
        messagingSenderId: _require('FIREBASE_MACOS_MESSAGING_SENDER_ID'),
        projectId: _require('FIREBASE_MACOS_PROJECT_ID'),
        storageBucket: _require('FIREBASE_MACOS_STORAGE_BUCKET'),
        androidClientId: _optional('FIREBASE_MACOS_ANDROID_CLIENT_ID'),
        iosClientId: _optional('FIREBASE_MACOS_CLIENT_ID'),
        iosBundleId: _require('FIREBASE_MACOS_BUNDLE_ID'),
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: _require('FIREBASE_WINDOWS_API_KEY'),
        appId: _require('FIREBASE_WINDOWS_APP_ID'),
        messagingSenderId: _require('FIREBASE_WINDOWS_MESSAGING_SENDER_ID'),
        projectId: _require('FIREBASE_WINDOWS_PROJECT_ID'),
        authDomain: _require('FIREBASE_WINDOWS_AUTH_DOMAIN'),
        storageBucket: _require('FIREBASE_WINDOWS_STORAGE_BUCKET'),
        measurementId: _optional('FIREBASE_WINDOWS_MEASUREMENT_ID'),
      );

  static String _require(String key) {
    final value = String.fromEnvironment(key);
    if (value.isEmpty) {
      throw StateError(
        'Missing $key. Provide it via --dart-define or your build system.',
      );
    }
    return value;
  }

  static String? _optional(String key) {
    final value = String.fromEnvironment(key);
    return value.isEmpty ? null : value;
  }
}
